version: "3"

name: hello-fastapi

services:
  database:
    image: postgres
    container_name: hello-fastapi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: hello-postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: hello-fastapi-redis
    ports:
      - "6397:6397"
    command:
      redis-server --requirepass mypassword --port 6379

volumes:
  postgres-volume:
